stages:
  - build

cache:
  paths:
    - node_modules/

before_script:
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build:
  stage: build
  only:
    refs:
      - main
  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - ssh root@175.178.22.67 "cd /www/my-server/my-express && git pull && yarn install"
    - ssh $SERVER_USER@$SERVER_HOST "pm2 stop my-express"
    - ssh $SERVER_USER@$SERVER_HOST "pm2 start /www/my-server/my-express/src/index.js --name my-express"